### PR TITLE
Remove contents of build/ from source control

### PR DESCRIPTION
**Pull request by jus1in**
I think the build folder should be removed from source control. It is not source code because it is created by the build process, so there is no point in versioning it. All it does is create merge conflicts.

I've created this pull request to discuss this.

### CODE REVIEW

**Comment by jus1in** [comment]
You would probably have to change your deployment process to build the code if it doesn't already.

**Comment by dkoes** [comment]
For CDN hosting we need to output of the builds to be in git somehow.  Originally I had a release directory that was distinct from the build directory.  Perhaps if we went back to that system..

**Comment by jus1in** [comment]
Has to be in Git? That's inconvenient.
Wouldn't creating a release directory just mean that there is a file constantly changing in the release directory instead of the build directory?

**Comment by dkoes** [comment]
I meant to have a discussion about this at the group meeting but forgot.. let's discuss at the next meeting.

**Pull request closed without merging**
